### PR TITLE
GH80: Performance improvements

### LINKED ISSUE #80: Slow performance with big/many files.
Currently we only get the whole buffer from VSCode on updates, so it’s hard to actually know what have been changed. Once LSP us taken into use in C# extension, we will get incremental updates.

We should make sure incremental updates don’t do script analysis and codegen when not needed.

Also, we should figure out how to improve perf when whole buffer is submitted.

### PR DESCRIPTION
**Pull request by mholo65**
Fixes #80 

I'm using a simple benchmark which uses the whole pipe as OmniSharp would.

Example code:
```csharp
public class BakeryGeneration
    {
        private readonly IScriptGenerationService _service;
        private readonly FileChange _fileChange;

        public BakeryGeneration()
        {
            _service = new ScriptGenerationClient("./Cake.Bakery.exe", Path.GetFullPath("./"), new LoggerFactory());
            _fileChange = new FileChange
            {
                Buffer = @"var target = Argument(""target"", ""Default"");

Task(""Default"")
  .Does(() =>
{
  Information(""Hello World!"");
});

RunTarget(target);",
                FileName = "build.cake",
                FromDisk = false
            };
        }

        [Benchmark]
        public CakeScript Generate() => _service.Generate(_fileChange);
    }

    public static class Program
    {
        public static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<BakeryGeneration>();
        }
    }
```

Start.

|   Method |     Mean |    Error |   StdDev |
|--------- |---------:|---------:|---------:|
| Generate | 244.6 ms | 10.91 ms | 32.17 ms |

### CODE REVIEW

**Comment by mholo65** [comment]
Moved addinRoot, cakeRoot and hostObject initialization to constructor.


|   Method |     Mean |    Error |   StdDev |
|--------- |---------:|---------:|---------:|
| Generate | 191.0 ms | 3.754 ms | 6.769 ms |

**Comment by mholo65** [comment]
Cahe generated aliases.

|   Method |     Mean |    Error |   StdDev |
|--------- |---------:|---------:|---------:|
| Generate | 170.6 ms | 3.365 ms | 7.996 ms |

**Comment by gep13** [comment]
@mholo65 checks you go! 😄

**Comment by mholo65** [comment]
Compress source before sending over the wire.

|   Method |     Mean |    Error |   StdDev |   Median |
|--------- |---------:|---------:|---------:|---------:|
| Generate | 36.40 ms | 1.230 ms | 3.528 ms | 35.25 ms |

**Comment by mholo65** [comment]
I'd like to revisit and remove the cache generated aliases, as it adds a performance hit when adding to cache.

**Comment by mholo65** [comment]
Nah, without caching of the generated DSL, we'll enp up with this. I think it's better to take the performance hit once (when loading a new addin) than everytime...

|   Method |     Mean |    Error |   StdDev |
|--------- |---------:|---------:|---------:|
| Generate | 62.90 ms | 1.927 ms | 5.652 ms |

**Comment by mholo65** [comment]
@cake-build/cake-team I think this is ready for review....

This will be a breaking change between 0.1.x and 0.2.x... I.e. OmniSharp would need to be updated before this can be taken into use... I.e. we need to sync release with OmniSharp release.

**Pull request merged**
