### PR TITLE
Make sure a reference to System.Linq is present.

### LINKED ISSUE #147: Reference to System.Linq missing
image

### PR DESCRIPTION
**Pull request by bjorkstromm**
Fixes #147

### CODE REVIEW

**Review by nils-a — APPROVED** [review]
LGTM!

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by gep13** [comment]
@nils-a @augustoproiete I will take care of this tomorrow morning, and get a 0.7.2 shipped.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@bjorkstromm thanks for getting this added!

**Pull request merged**
