### PR TITLE
Move to signing service v2

### PR DESCRIPTION
**Pull request by mholo65**

### CODE REVIEW

**Comment by mholo65** [comment]
@onovotny I had problems signing locally (I used user+pass from LastPass, but still no luck). So I thought I'll just push a PR and ask for help 😄 

This is the output I get:
```
========================================
Sign-Binaries
========================================
Executing task: Sign-Binaries
Executing: "C:/Program Files/dotnet/dotnet.exe" --version
2.0.2
Signing C:/Users/mb/src/gh/bakery/BuildArtifacts/Packages/NuGet/Cake.Bakery.0.2.0-new-signing-serv0001.nupkg...
Executing: "C:/Program Files/dotnet/dotnet.exe" "C:/Users/mb/src/gh/bakery/tools/SignClient.0.9.0/tools/netcoreapp2.0/SignClient.dll" sign -c "C:/Users/mb/src/gh/bakery/signclient.json" -i "C:/Users/mb/src/gh/bakery/BuildArtifacts/Packages/NuGet/Cake.Bakery.0.2.0-new-signing-serv0001.nupkg" -f "C:/Users/mb/src/gh/bakery/signclient.filter" -s "[REDACTED]" -r "[REDACTED]" -h "dual" -n "Cake" -d "Cake (C# Make) is a cross platform build automation system." -u "https://cakebuild.net"
Server returned non Ok response: 400 Bad Request
An error occurred when executing task 'Sign-Binaries'.
```

**Comment by onovotny** [comment]
Can you try getting rid of `-h "dual"`, you don't need it currently.

**Comment by mholo65** [comment]
@onovotny Thanks, that worked! I guess no one needs dual signing these days anymore?

**Comment by onovotny** [comment]
XP was the only reason for dual signing left

**Pull request merged**
