### PR TITLE
(GH-129) When using .NET Global tool, resolve Cake.dll to netcoreapp3.1

### PR DESCRIPTION
**Pull request by augustoproiete**
Bakery currently needs `Cake.Core` and `Cake.Common` targeting `netstandard2.0` only as per @bjorkstromm's comment https://github.com/cake-build/bakery/issues/129#issuecomment-792359060

### CODE REVIEW

**Review by bjorkstromm — APPROVED** [review]
LGTM!

@augustoproiete, have you tested that this works?

**Comment by nils-a** [comment]
I have tested it and it does work - but only for Cake 1.1.0. (Neiter Cake 1.0.0, nor Cake 0.38.5 will work - since none of them ship `netcoreapp3.1`)

Would it be possible to change the glob from `netcoreapp3.1` to something matching `netcoreapp3*`? If we manage that I guess the change would be compatible with older versions, too.

**Comment by augustoproiete** [comment]
@bjorkstromm Yes, tested with 1.1.0.

@nils-a Good catch. I updated the PR earlier this morning to resolve `netcoreapp2.1` as well:

Cake Tool 1.1.0 resolves to:

```
C:/Users/augustoproiete/.dotnet/tools/.store/cake.tool/1.1.0/cake.tool/1.1.0/tools/netcoreapp3.1/any/Cake.dll
```

---

- Cake Tool 0.38.5 resolves to:

```
C:/Users/augustoproiete/.dotnet/tools/.store/cake.tool/0.38.5/cake.tool/0.38.5/tools/netcoreapp2.1/any/Cake.dll
```

**Review by bjorkstromm — APPROVED** [review]
Awesome! Thanks @augustoproiete

**Review by nils-a — APPROVED** [review]
LGTM

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@augustoproiete I have rebased and merged this into a hotfix branch here: https://github.com/cake-build/bakery/commit/c1e22a1e66bee406bf1e042d054db743196f6a1e

As a result, going to close out this PR.

**Pull request closed without merging**
