### PR TITLE
Update project to use .NET 6.0

### PR DESCRIPTION
**Pull request by gep13**
This is a follow up PR to this one:

https://github.com/cake-build/bakery/pull/138

Since we aren't able to push changes back to source of PR.

### CODE REVIEW

**Comment by augustoproiete** [comment]
Build is failing with `Could not execute because the application was not found or a compatible .NET SDK is not installed` - could be related to this bug: https://github.com/dotnet/sdk/issues/14916

**Comment by nils-a** [comment]
The two commits, [d475887](https://github.com/cake-build/bakery/pull/143/commits/d4758876674ddcf2b2af817ba7ca27b094e4d0c2) and [5dddaae](https://github.com/cake-build/bakery/pull/143/commits/5dddaaeb9cf54a06d1714d238b906242ed757578), can be reverted, when Cake.Recipe is updated to a version that incorporates https://github.com/cake-contrib/Cake.Recipe/pull/869

**Comment by nils-a** [comment]
I'm done for the moment. 
Currently, integration tests fail on AppVeyor. The error is 

> It was not possible to find any compatible framework version.

**Review by augustoproiete — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@augustoproiete you bray me to it! I was going to try the new AppVeyor image this morning. Do we still need the additional step to install the SDK? Shouldn't that already be on the image?

**Review by nils-a — APPROVED** [review]
LGTM, though I think we should `fixup` some of the trial-and-error-commits we did 😉

**Comment by gep13** [comment]
Agreed! This is hopefully going to be done tonight, but will see how my time goes. Would be good to get this shipped out.

**Comment by gep13** [comment]
@augustoproiete @nils-a let's do this thing! 😄

**Pull request merged**
