### PR TITLE
Multi-target libraries to also include ns2

### PR DESCRIPTION
**Pull request by mholo65**

### CODE REVIEW

**Review by patriksvensson — APPROVED** [review]

**Review by patriksvensson — CHANGES_REQUESTED** [review]
CI failing. Fix that 😁

**Comment by gep13** [comment]
@mholo65 @patriksvensson I have fixed the CI build for Bakery.

We should be in a position to get this merged now.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by mholo65** [comment]
Thank you @gep13!

**Pull request merged**
